# Generated by Django 4.1.5 on 2024-01-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytics',
        ),
    ]
