# Generated by Django 4.1.5 on 2024-01-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.FloatField(default=0),
        ),
    ]
