# Generated by Django 4.1.5 on 2024-01-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_retail_price_product_wholesale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
