# Generated by Django 4.1.5 on 2024-01-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='retail_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_price',
        ),
    ]
