# Generated by Django 4.1.5 on 2024-01-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_retail_price_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_inclusive',
            field=models.BooleanField(default=True, help_text='Is VAT inclusive for this product?'),
        ),
    ]
