# Generated by Django 4.1.5 on 2024-01-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_vat_inclusive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vat_inclusive',
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ZERO', 'Zero')], default='GENERAL', max_length=100, verbose_name='VAT rates'),
        ),
    ]
