# Generated by Django 4.1.5 on 2024-01-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_vat_inclusive_product_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buying_price',
            field=models.FloatField(default=0),
        ),
    ]
