# Generated by Django 4.1.5 on 2024-01-18 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_remove_product_vat_inclusive_product_vat_rate'),
        ('customers', '0002_customer_loyalty_points'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_total', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('discount_percentage', models.FloatField(default=0)),
                ('amount_payed', models.FloatField(default=0)),
                ('amount_change', models.FloatField(default=0)),
                ('customer', models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
            ],
            options={
                'db_table': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total_detail', models.FloatField()),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
                ('sale', models.ForeignKey(db_column='sale', on_delete=django.db.models.deletion.DO_NOTHING, to='sales.sale')),
            ],
            options={
                'db_table': 'SaleDetails',
            },
        ),
    ]
