# Generated by Django 4.1.5 on 2024-01-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_tax_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
