# Generated by Django 4.1.5 on 2024-01-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_venta_saledetail_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saledetail',
            old_name='price',
            new_name='unit_price',
        ),
    ]
