# Generated by Django 4.1.5 on 2024-01-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='profit',
            new_name='sale_profit',
        ),
    ]
