# Generated by Django 4.1.5 on 2024-01-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_price_saledetail_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saledetail',
            old_name='unit_price',
            new_name='price',
        ),
    ]
