# Generated by Django 4.1.5 on 2024-01-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_unit_price_saledetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
    ]
