# Generated by Django 4.1.5 on 2024-01-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_profit_sale_sale_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_profit',
        ),
    ]
