# Generated by Django 4.1.5 on 2024-01-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_discount_amount_sale_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tax_percentage',
        ),
    ]
