# Generated by Django 4.1.5 on 2024-01-19 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_sale_sale_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(db_column='sale', on_delete=django.db.models.deletion.DO_NOTHING, related_name='saledetail_set', to='sales.sale'),
        ),
    ]
